---
title: "Contact US"

output: html_document
---


<style type="text/css">
body {
  font-size: 12pt;
}

h1, h2, h3{
  color: #4682B4;
  hyphens: none;
}

#TOC {
  margin: 25px 0px 20px 0px;
}

hr {
  border-top: 5px solid #F0F8FF;
}

.clearfix {
  overflow: auto;
}

img {
  margin-right: 20px;
  box-shadow: 5px 5px 10px #ccc;
}

</style>





<style>

.try {
  width: 100px;
  margin: 2px;
  height: 100px;
  display: flex;
  background-color: purple;
  margin: 20px;
  animation: abc 2s infinite alternate;
}

@keyframes abc {
  from {border: 0px; 
    background-color:purple; transform:rotate(90deg)}
  to {border-radius: 50%; background-color: red}
	
}

</style>

<div class="try">

</div>




<br>

Our Department is located in beautiful city of Greensboro, North Carolina. 


Graham Bldg 1009 Spring Garden St, <br>
Greensboro, NC 27412


<style>

.primary-btn:hover {
padding: 3px;
color: blue;
background-color: grey;
}

}

</style>

<a class= "primary-btn" href = "https://ges.uncg.edu" target="_blank" > Click here </a> to visit the department's website

If you have any other inquiries, please contact Dr. Praskievicz.  sjpraski AT uncg.edu

<br>






<style>
  .google-maps {
    position: relative;
    padding-bottom: 75%; // This is the aspect ratio
    height: 0;
    overflow: hidden;
  }
  .google-maps iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100% !important;
    height: 100% !important;
  }
  
  
</style>

<div class="google-maps">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1917.6720446450565!2d-79.80803956759858!3d36.06600396488527!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8853191551a62be1%3A0x2064bd77398457ec!2sGraham%20Bldg%2C%201009%20Spring%20Garden%20St%2C%20Greensboro%2C%20NC%2027412!5e0!3m2!1sen!2sus!4v1695313132989!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

</div>



<br>

### You can also use the following form to contact us

<br>

<style type="text/css">

div ul {
text-decoration:none;

list-style-type: none;

}

.button {
list-style-type: none;

}

</style>

<div >



<div >



<form action="https://formspree.io/f/xyyqlvee" method="POST">

  <ul>
    <li>
      <label for="name">Name:</label>
      <input type="text" id="name" name="user_name" />
    </li>
    
    <br> 
    
    <li>
      <label for="mail">Email:</label>
      <input type="email" id="mail" name="user_email" />
    </li>
    
     <br> 
    
    
    <label for="degree">What degree would you like to puruse:</label>
  <select id="degree" name="degrees">
    <option value="Bacehlor"> Bachelor Degree </option>
    <option value="Masters">Master Degree</option>
    <option value="Ph.D">Ph.D Degree </option>
    
  </select>
    
    
    <li>
      <label for="msg">Message:</label>
      <textarea id="msg" name="user_message"></textarea>
    </li>
  </ul>


 <button type="submit">Send</button>
</li>

</form>


</div >